# Домашнее задание №5

### Задание №1 (1,5 балла)

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [1]:
import numpy as np
a = np.array([2, 4, 6, 8, 10, 12])
b = np.array([7, 11, 15, 18, 23, 29])
(a + b) ** 2

array([  81,  225,  441,  676, 1089, 1681])

$2.$ Выведите все элементы из первого массива, которые стоят на тех местах, где элементы второго массива больше 12 и дают остаток 3 при делении на 5.

In [2]:
b[b>12]
a[np.arange(b.shape[0])%5==3]

array([8])

*3.* Для первого массива найдите остатки от деления на 2, а для второго --- на 3. Для каждого получившегося массива выведите его уникальные значения (см. семинар).

In [3]:
np.unique(a%2)

array([0])

In [4]:
np.unique(b%3)

array([0, 1, 2])

### Задание №2 (1,5 балла)

Найдите интересный для вас датасет. Например, можно выбрать датасет [тут](http://data.un.org/Explorer.aspx) или [тут](https://hls.harvard.edu/library/research/find-a-database/). Если выскакивают ошибки при считывании таблицы, попробуйте их погуглить и решить проблему!

1. Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
2. Проанализируйте и прокомментируйте содержательно получившиеся результаты
    - недостаточно написать фразы формата "Средний возраст = 60, а минимальный = 20", следует дать пояснение, что это значит и какие выводы можно сделать в рамках датасета
3. Все комментарии оформляйте строго в ячейках формата Markdown
    - для этого надо в выпадающем окошке сверху для текущей ячейки сменить тип Code на Markdown
    ![](https://i.imgur.com/vl7Fmg9.png)

In [5]:
dataset = np.loadtxt("file.txt", dtype=int)

In [6]:
dataset

array([[2001, 5000,  255,  222],
       [2002, 3050,   66,  124],
       [2003, 7001,  124,  665],
       [2004, 2064,  777,  756],
       [2005, 2352,  242,  127],
       [2006, 1245,  774,  623],
       [2007, 5478,  923,  765],
       [2008, 8678,  564, 1000],
       [2009, 9456,  456,  234],
       [2010, 2135,  785,  333],
       [2011, 6834,  453,  645],
       [2012, 3256,  324,  888],
       [2013, 5687,  864,  954],
       [2014, 1000,   12,  743],
       [2015, 5472,   43,  658],
       [2016, 2351,   66,  845],
       [2017, 1064,   71,  126],
       [2018, 9633,   87,  753],
       [2019, 1248,   24,  123],
       [2020, 9346,    6,  654],
       [2021, 7523,   46,  578]])

# Среднее значение

In [7]:
np.mean(dataset[:, 1])

4755.857142857143

# Медиана

In [8]:
np.median(dataset[:, 2])

242.0

# Размах

In [9]:
np.max(dataset[:, 0])-np.min(dataset[:, 0])

20

# Дисперсия

In [10]:
np.var(dataset[:, 3])

83743.65079365078