In [1]:
import numpy as np

# Домашнее задание на повторение numpy
В задании все пункты необходимо выполнить с помощью numpy, без использования циклов/map/и тд! 

Задание выполняется __самостоятельно__. Категорически запрещено пользоваться чужими решениями заданий (даже смотреть их), в том числе, размещенными в открытых источниках (если таковые обнаружатся). При обнаружении списывания выставляется 0 за задание (в случае списывания у одногруппника/однокурскника - __ему/ей тоже__), а также подается докладная записка в учебный офис. Проверка на списывание проводится и автоматическими средствами, и вручную.

### История

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную в семестре оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу некоторого курса выполнить эту непростую работу с помощью numpy :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [2]:
marks = np.loadtxt("https://raw.githubusercontent.com/nadiinchi/iad2019/master/materials/data_hw1.txt")

In [3]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### Число студентов (1 балл)
Сколько студентов в группе семинариста?

In [4]:
# Записать ответ в переменную num_studs
num_studs = marks.shape[0]

In [5]:
print(num_studs)

28


### Очень сложная проверочная, или просто добрый семинарист (1.5 балла)
Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил перенормировать баллы за эту проверочную на максимум по группе (поделить на максимум и умножить на 10) - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную?

In [6]:
# Записать ответ в переменную max_mark
max_mark = marks[: , 0].max()

In [7]:
print(max_mark)

7.0


Разделите первый столбец на max_mark (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [8]:
first_table = marks[: , 0] / max_mark * 10

In [9]:
print(first_table)

[10.          0.          4.28571429  4.85714286  9.71428571 10.
  8.57142857  0.          7.14285714  0.          4.28571429  5.71428571
  0.          8.57142857  7.14285714  0.         10.          6.42857143
  0.          0.          0.          8.57142857  9.28571429 10.
  0.         10.          4.28571429  5.        ]


In [10]:
marks[: , 0] = np.around(first_table, decimals = 1) 
marks

array([[10. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 4.3,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ],
       [ 4.9,  1.3,  7. ,  3.4,  0. ,  9.4,  9. ],
       [ 9.7,  9.1,  8.2,  0. ,  0. ,  7.9,  7.9],
       [10. , 10. , 10. ,  9. ,  9.5, 10. ,  8. ],
       [ 8.6, 10. ,  9.7,  8.7,  7. ,  8.5,  9.7],
       [ 0. ,  9.3,  5.7,  0. ,  0. ,  0. ,  0. ],
       [ 7.1, 10. , 10. ,  9.9, 10.5, 10. ,  9. ],
       [ 0. ,  8.7,  8. ,  9.7, 10. ,  9.5, 10. ],
       [ 4.3,  6.9,  7.9,  0. ,  0. ,  0. ,  0. ],
       [ 5.7, 10. , 10. ,  9.9,  9.7, 10. ,  9. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 8.6,  5. , 10. ,  9.7, 10. , 10. ,  8. ],
       [ 7.1, 10. ,  9. ,  7. ,  7.9, 10. ,  9. ],
       [ 0. ,  6. ,  7.4,  0. ,  0. ,  0. ,  0. ],
       [10. , 10. , 10. ,  9.7, 10. , 10. , 10. ],
       [ 6.4,  8.7, 10. ,  9.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  5.6,  8.7,  0. ,

### Подсчет накопленной оценки (1.5 балла)
Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться np.mean). Накопленная оценка есть 0.3\*Проверочные + 0.4\*Домашние + 0.3\*Коллоквиум. Вычислите накопленные оценки и добавьте их в последний столбец матрицы (нужно добавить еще один новый столбец).

In [11]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = np.array([0.3, 0.4, 0.3])
weights

array([0.3, 0.4, 0.3])

In [12]:
a = np.around(np.mean(marks[:, 0:3], axis = 1), decimals = 1)
a

array([ 9.3,  3.5,  6.7,  4.4,  9. , 10. ,  9.4,  5. ,  9. ,  5.6,  6.4,
        8.6,  0. ,  7.9,  8.7,  4.5, 10. ,  8.4,  0. ,  4.8,  0. ,  9.5,
        9.2,  9.9,  5.9,  8.8,  7.7,  8.1])

In [13]:
b = np.around(np.mean(marks[:, 3:6], axis = 1), decimals = 1)
b

array([ 0.7,  3. ,  8.1,  4.3,  2.6,  9.5,  8.1,  0. , 10.1,  9.7,  0. ,
        9.9,  0. ,  9.9,  8.3,  0. ,  9.9,  3.2,  0. ,  0. ,  0. ,  8.9,
       10.1,  9.4,  3.2,  5.5, 10. , 10. ])

In [14]:
c = marks[:, 6]

In [15]:
acc_mark = weights[0]*a+weights[1]*b+weights[2]*c
acc_mark = acc_mark[:, np.newaxis]
marks = np.hstack((marks, acc_mark))
marks

array([[10.  ,  8.  , 10.  ,  0.  ,  0.  ,  2.1 ,  1.5 ,  3.52],
       [ 0.  ,  6.  ,  4.4 ,  4.  ,  0.  ,  5.  ,  4.3 ,  3.54],
       [ 4.3 ,  7.  ,  8.7 ,  7.6 ,  7.  ,  9.7 , 10.  ,  8.25],
       [ 4.9 ,  1.3 ,  7.  ,  3.4 ,  0.  ,  9.4 ,  9.  ,  5.74],
       [ 9.7 ,  9.1 ,  8.2 ,  0.  ,  0.  ,  7.9 ,  7.9 ,  6.11],
       [10.  , 10.  , 10.  ,  9.  ,  9.5 , 10.  ,  8.  ,  9.2 ],
       [ 8.6 , 10.  ,  9.7 ,  8.7 ,  7.  ,  8.5 ,  9.7 ,  8.97],
       [ 0.  ,  9.3 ,  5.7 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.5 ],
       [ 7.1 , 10.  , 10.  ,  9.9 , 10.5 , 10.  ,  9.  ,  9.44],
       [ 0.  ,  8.7 ,  8.  ,  9.7 , 10.  ,  9.5 , 10.  ,  8.56],
       [ 4.3 ,  6.9 ,  7.9 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.92],
       [ 5.7 , 10.  , 10.  ,  9.9 ,  9.7 , 10.  ,  9.  ,  9.24],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 8.6 ,  5.  , 10.  ,  9.7 , 10.  , 10.  ,  8.  ,  8.73],
       [ 7.1 , 10.  ,  9.  ,  7.  ,  7.9 , 10.  ,  9.  ,  8.63],
       [ 0.  ,  6.  ,  7.

### Студенты, которых, вероятно, отчислят (1.5 балла)

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [16]:
np.sum([True, False, True]) # 2 значения True

2

Также обратим внимание на операцию поэлементного сравнения, возвращающую массив из True и False:

In [17]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 3])
print(a == b)
print(a > b)

[False False  True]
[False False False]


In [18]:
marks

array([[10.  ,  8.  , 10.  ,  0.  ,  0.  ,  2.1 ,  1.5 ,  3.52],
       [ 0.  ,  6.  ,  4.4 ,  4.  ,  0.  ,  5.  ,  4.3 ,  3.54],
       [ 4.3 ,  7.  ,  8.7 ,  7.6 ,  7.  ,  9.7 , 10.  ,  8.25],
       [ 4.9 ,  1.3 ,  7.  ,  3.4 ,  0.  ,  9.4 ,  9.  ,  5.74],
       [ 9.7 ,  9.1 ,  8.2 ,  0.  ,  0.  ,  7.9 ,  7.9 ,  6.11],
       [10.  , 10.  , 10.  ,  9.  ,  9.5 , 10.  ,  8.  ,  9.2 ],
       [ 8.6 , 10.  ,  9.7 ,  8.7 ,  7.  ,  8.5 ,  9.7 ,  8.97],
       [ 0.  ,  9.3 ,  5.7 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.5 ],
       [ 7.1 , 10.  , 10.  ,  9.9 , 10.5 , 10.  ,  9.  ,  9.44],
       [ 0.  ,  8.7 ,  8.  ,  9.7 , 10.  ,  9.5 , 10.  ,  8.56],
       [ 4.3 ,  6.9 ,  7.9 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.92],
       [ 5.7 , 10.  , 10.  ,  9.9 ,  9.7 , 10.  ,  9.  ,  9.24],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 8.6 ,  5.  , 10.  ,  9.7 , 10.  , 10.  ,  8.  ,  8.73],
       [ 7.1 , 10.  ,  9.  ,  7.  ,  7.9 , 10.  ,  9.  ,  8.63],
       [ 0.  ,  6.  ,  7.

In [19]:
r = marks[:, -1]==0

In [20]:
np.sum(r)

3

### Студенты, которые получат автоматы (1.5 балла)
Автомат получат студенты, у которых накопленная оценка больше 7. Добавьте еще один столбец - в нем стоит 1, если студент получает автомат, и 0 иначе.

In [21]:
auto = (marks[:, - 1]>7).astype(int)

In [22]:
auto = auto[:, np.newaxis]
marks = np.hstack((marks, auto))

In [23]:
marks

array([[10.  ,  8.  , 10.  ,  0.  ,  0.  ,  2.1 ,  1.5 ,  3.52,  0.  ],
       [ 0.  ,  6.  ,  4.4 ,  4.  ,  0.  ,  5.  ,  4.3 ,  3.54,  0.  ],
       [ 4.3 ,  7.  ,  8.7 ,  7.6 ,  7.  ,  9.7 , 10.  ,  8.25,  1.  ],
       [ 4.9 ,  1.3 ,  7.  ,  3.4 ,  0.  ,  9.4 ,  9.  ,  5.74,  0.  ],
       [ 9.7 ,  9.1 ,  8.2 ,  0.  ,  0.  ,  7.9 ,  7.9 ,  6.11,  0.  ],
       [10.  , 10.  , 10.  ,  9.  ,  9.5 , 10.  ,  8.  ,  9.2 ,  1.  ],
       [ 8.6 , 10.  ,  9.7 ,  8.7 ,  7.  ,  8.5 ,  9.7 ,  8.97,  1.  ],
       [ 0.  ,  9.3 ,  5.7 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.5 ,  0.  ],
       [ 7.1 , 10.  , 10.  ,  9.9 , 10.5 , 10.  ,  9.  ,  9.44,  1.  ],
       [ 0.  ,  8.7 ,  8.  ,  9.7 , 10.  ,  9.5 , 10.  ,  8.56,  1.  ],
       [ 4.3 ,  6.9 ,  7.9 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.92,  0.  ],
       [ 5.7 , 10.  , 10.  ,  9.9 ,  9.7 , 10.  ,  9.  ,  9.24,  1.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 8.6 ,  5.  , 10.  ,  9.7 , 10.  , 10.  ,  8.  ,  8.73, 

### Студенты, которые будут освобождены от задач на экзамене (1.5 балла)
Семинарист решил, что первая половина группы в рейтинге по накопленной оценке будет освобождена от решения задач на экзамене. Выделите этих студентов в отдельный массив. Для этого надо отсортировать строки массива (np.argsort) и взять первую половину.

In [24]:
x = marks.copy()

In [25]:
x = np.hstack((x, (-x[:, -2])[:, np.newaxis]))

In [26]:
x

array([[10.  ,  8.  , 10.  ,  0.  ,  0.  ,  2.1 ,  1.5 ,  3.52,  0.  ,
        -3.52],
       [ 0.  ,  6.  ,  4.4 ,  4.  ,  0.  ,  5.  ,  4.3 ,  3.54,  0.  ,
        -3.54],
       [ 4.3 ,  7.  ,  8.7 ,  7.6 ,  7.  ,  9.7 , 10.  ,  8.25,  1.  ,
        -8.25],
       [ 4.9 ,  1.3 ,  7.  ,  3.4 ,  0.  ,  9.4 ,  9.  ,  5.74,  0.  ,
        -5.74],
       [ 9.7 ,  9.1 ,  8.2 ,  0.  ,  0.  ,  7.9 ,  7.9 ,  6.11,  0.  ,
        -6.11],
       [10.  , 10.  , 10.  ,  9.  ,  9.5 , 10.  ,  8.  ,  9.2 ,  1.  ,
        -9.2 ],
       [ 8.6 , 10.  ,  9.7 ,  8.7 ,  7.  ,  8.5 ,  9.7 ,  8.97,  1.  ,
        -8.97],
       [ 0.  ,  9.3 ,  5.7 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.5 ,  0.  ,
        -1.5 ],
       [ 7.1 , 10.  , 10.  ,  9.9 , 10.5 , 10.  ,  9.  ,  9.44,  1.  ,
        -9.44],
       [ 0.  ,  8.7 ,  8.  ,  9.7 , 10.  ,  9.5 , 10.  ,  8.56,  1.  ,
        -8.56],
       [ 4.3 ,  6.9 ,  7.9 ,  0.  ,  0.  ,  0.  ,  0.  ,  1.92,  0.  ,
        -1.92],
       [ 5.7 , 10.  , 10.  ,  9.9 ,  9.7 , 

In [27]:
idx = np.argsort(x, axis=0)

In [28]:
x = x[idx[:, -1], :-1]

In [29]:
x[:x.shape[0]//2, :]

array([[10.  , 10.  , 10.  ,  9.7 , 10.  , 10.  , 10.  ,  9.96,  1.  ],
       [ 9.3 ,  8.7 ,  9.5 , 10.5 ,  9.8 , 10.  , 10.  ,  9.8 ,  1.  ],
       [10.  ,  9.7 , 10.  ,  8.1 , 10.  , 10.  ,  9.5 ,  9.58,  1.  ],
       [ 7.1 , 10.  , 10.  ,  9.9 , 10.5 , 10.  ,  9.  ,  9.44,  1.  ],
       [ 5.7 , 10.  , 10.  ,  9.9 ,  9.7 , 10.  ,  9.  ,  9.24,  1.  ],
       [10.  , 10.  , 10.  ,  9.  ,  9.5 , 10.  ,  8.  ,  9.2 ,  1.  ],
       [ 4.3 ,  8.7 , 10.  ,  9.4 , 10.7 , 10.  ,  9.  ,  9.01,  1.  ],
       [ 8.6 , 10.  ,  9.7 ,  8.7 ,  7.  ,  8.5 ,  9.7 ,  8.97,  1.  ],
       [ 5.  ,  9.3 , 10.  ,  9.9 , 10.  , 10.  ,  8.  ,  8.83,  1.  ],
       [ 8.6 ,  5.  , 10.  ,  9.7 , 10.  , 10.  ,  8.  ,  8.73,  1.  ],
       [ 7.1 , 10.  ,  9.  ,  7.  ,  7.9 , 10.  ,  9.  ,  8.63,  1.  ],
       [ 0.  ,  8.7 ,  8.  ,  9.7 , 10.  ,  9.5 , 10.  ,  8.56,  1.  ],
       [ 8.6 , 10.  , 10.  ,  9.7 ,  7.  , 10.  ,  7.  ,  8.51,  1.  ],
       [ 4.3 ,  7.  ,  8.7 ,  7.6 ,  7.  ,  9.7 , 10.  ,  8.25, 

### Сложность заданий (1.5 балла)
Наконец, семинарист хочет оценить сложность заданий, проверочных и коллоквиума по своей особой системе. Он присвоил каждому студенту вес (веса суммируются в 1) и хочет посчитать для каждого задания, проверочной и коллоквиума среднюю оценку с весами.
Пример, что имеется в виду: если есть 4 студента с весами [0.1, 0.2, 0.3, 0.4] и оценками [3, 7, 9, 10], то средняя оценка за задание с весами получится 

In [30]:
0.1 * 3 + 0.2 * 7 + 0.3 * 9 + 0.4 * 10 

8.4

Веса:

In [31]:
weights = np.array([1.]*7+[2.]*4+[3.]*7+[4.]*(marks.shape[0]-18))
# разделите веса на их сумму, чтобы они суммировались к 1
weights = 

SyntaxError: invalid syntax (<ipython-input-31-315289e08d56>, line 3)

Посчитайте указанным образом сложность каждого "столбца".